<div class="field">
    <label>Username</label>
    <div>
        <input name="username" type="text" class="kontrol-form">
    </div>
</div>

<div class="field">
    <label>Password</label>
    <div>
        <input name="pass" type="password" class="kontrol-form">
    </div>
</div>

<div class="button">
    <input name="login" type="submit" class="kontrol-form" value="SIGN IN">
    <input type="reset" class="kontrol-form" value="RESET">
</div>